initial commit
kugemi/CLabs pull request #30
Opened 2021-11-13 16:19 UTC by Triggered831

2021-11-13 17:59 UTC, kugemi requested changes
Нужно переделать обе лабы. Ты не понял задание

2021-11-13 17:59 UTC, kugemi commented on lab6/Hohrin/laba6.cpp
> +	int binaryArray[100] = { 0 };
Обе лабы делаются с помощью операции "битовый сдвиг". Никаких массивов ни в 6, ни в 7 быть не должно

2021-11-14 13:32 UTC, Triggered831 commented on lab6/Hohrin/laba6.cpp
> +	int binaryArray[100] = { 0 };
переделал 6, пока что работает только вывод влево, и почему то если изначально ввести большое число, то после сдвига вывод в двоичной системе ломается

2021-11-14 13:34 UTC, Triggered831 commented on lab6/Hohrin/laba6.cpp
> +	int binaryArray[100] = { 0 };
![image](https://user-images.githubusercontent.com/60940169/141683406-f3e7ede3-929d-4277-955d-4b44527cd277.png)

2021-11-14 13:35 UTC, Triggered831 commented on lab6/Hohrin/laba6.cpp
> +	int binaryArray[100] = { 0 };
пробовал заменить int на long long int, но все равно не работает

2021-11-14 19:02 UTC, kugemi requested changes

2021-11-14 19:02 UTC, kugemi commented on lab6/Hohrin/laba6.cpp
> +﻿#include <conio.h>
![image](https://user-images.githubusercontent.com/61092799/141694664-d20c1f81-eba5-418f-aea9-c7ab9c7c39fe.png)
тут что-то явно не так

2021-11-14 19:02 UTC, kugemi commented on lab7/Hohrin/laba7.cpp
> +﻿#include <conio.h>
эту лабу надо обязательно делать с помощью битового сдвига

2021-11-20 20:10 UTC, kugemi requested changes

2021-11-20 20:10 UTC, kugemi commented on lab8/Hohrin/laba8.cpp
> +	trigger = 0;
ты после каждой проверки не зануляешь эту переменную, из-за этого неправильный результат

2021-11-28 17:54 UTC, kugemi requested changes

2021-11-28 17:54 UTC, kugemi commented on lab9/Hohrin/laba9.cpp
> +﻿#include <iostream>
это 11 лаба, а не 9
и она сделана неправильно - нужно чтение из файла и динамическое выделение памяти
в 9 тоже нужно обязательно динамическое выделение

2021-12-12 12:09 UTC, closed without merging