first
kugemi/CLabs pull request #31
Opened 2021-11-13 19:16 UTC by limonite

2021-11-16 10:12 UTC, kugemi requested changes

2021-11-16 10:12 UTC, kugemi commented on lab7/Bryzgalov/лаб 7.cpp
> +	int itemsNum[1022]= {0};
Почему 1022? Ты не сможешь решить эту задачу больше чем для 32 предметов. И для чего вообще нужен этот массив?

2021-11-17 15:52 UTC, limonite commented
убрал массив, уменьшил кол-во предметов

2021-11-18 20:33 UTC, kugemi approved these changes

2021-11-18 20:33 UTC, merged