privet Georgiy
kugemi/CLabs pull request #8
Opened 2021-10-24 21:33 UTC by Kirill11656

2021-10-24 23:56 UTC, kugemi commented on lab5/Melnikov/Лаба 5 Мельников.cpp
> +			numbOfSymbolsInWord[numbOfWords] = numbOfSymbols;
Если тебе кажется, что в том, чтобы выделить память в стеке, а потом ее не использовать, нет никаких проблем, то считай, что ну это же легче в сдачи мне лабы

2021-10-25 00:03 UTC, Kirill11656 commented on lab5/Melnikov/Лаба 5 Мельников.cpp
> +	int symbol;
Короче, не знаю, куда написать. Во втором коммите все норм кроме массива и той переменной, которая с _1?

2021-11-12 17:13 UTC, kugemi requested changes
есть что переделать

2021-11-12 17:13 UTC, kugemi commented on lab5/Melnikov/Лаба 5 Мельников.cpp
> +	int numbOfWords = -1;
опять костыль, только в другом месте... напиши код так, чтобы лишний раз переменная `numbOfWords` не увеличивалась

2021-11-12 17:15 UTC, Kirill11656 commented on lab5/Melnikov/Лаба 5 Мельников.cpp
> +	int numbOfWords = -1;
она нигде ЛИШНИЙ РАЗ не увеличивается

2021-11-12 17:15 UTC, Kirill11656 commented on lab5/Melnikov/Лаба 5 Мельников.cpp
> +	int numbOfWords = -1;
она считает количество слов

2021-11-12 17:20 UTC, Kirill11656 commented on lab5/Melnikov/Лаба 5 Мельников.cpp
> +	// ����������, � ��� ���������
Я уже на все менял. Не работает. В этом комменте ничего важного

2021-11-12 17:22 UTC, Kirill11656 commented on lab5/Melnikov/Лаба 5 Мельников.cpp
> +	int numbOfWords = -1;
Георгий, ты докапываешься до этой ошибки уже который раз (и то, во всех вариантах все работало) и, прошу заметить, у остальных ты принял. Ради справедливости, прими и у меня

2021-11-12 17:28 UTC, kugemi commented on lab5/Melnikov/Лаба 5 Мельников.cpp
> +	int numbOfWords = -1;
как она может не увеличиваться лишний раз, когда ты начинаешь увеличивать ее с -1?

2021-12-05 15:54 UTC, kugemi approved these changes
Ладно

2021-12-05 15:54 UTC, merged

2021-12-05 15:57 UTC, Kirill11656 commented
Спасибо)